import { getGeoData } from "../src/client/js/formHandler";

global.fetch = jest.fn(() =>
  Promise.resolve({
    json: () =>
      Promise.resolve({
        totalResultsCount: 23,
        geonames: [
          {
            adminCode1: "07",
            lng: "77.23149",
            geonameId: 1273294,
            toponymName: "Delhi",
            countryId: "1269750",
            fcl: "P",
            population: 10927986,
            countryCode: "IN",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "DL",
            },
            countryName: "India",
            fcodeName: "seat of a first-order administrative division",
            adminName1: "Delhi",
            lat: "28.65195",
            fcode: "PPLA",
          },
          {
            adminCode1: "CA",
            lng: "-120.77854",
            geonameId: 5342522,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 10755,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "CA",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "California",
            lat: "37.43216",
            fcode: "PPL",
          },
          {
            adminCode1: "GA",
            lng: "-82.67403",
            geonameId: 4191253,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "GA",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Georgia",
            lat: "33.91373",
            fcode: "PPL",
          },
          {
            adminCode1: "IL",
            lng: "-90.25595",
            geonameId: 4236954,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "IL",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Illinois",
            lat: "39.04532",
            fcode: "PPL",
          },
          {
            adminCode1: "LA",
            lng: "-91.49317",
            geonameId: 4321929,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 2900,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "LA",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Louisiana",
            lat: "32.45764",
            fcode: "PPL",
          },
          {
            adminCode1: "CO",
            lng: "-104.01802",
            geonameId: 5419324,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "CO",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Colorado",
            lat: "37.64224",
            fcode: "PPL",
          },
          {
            adminCode1: "MO",
            lng: "-91.34765",
            geonameId: 4383702,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "MO",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Missouri",
            lat: "38.12838",
            fcode: "PPL",
          },
          {
            adminCode1: "OK",
            lng: "-99.67649",
            geonameId: 4534986,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "OK",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Oklahoma",
            lat: "35.17477",
            fcode: "PPL",
          },
          {
            adminCode1: "TX",
            lng: "-97.39555",
            geonameId: 4685810,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "TX",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Texas",
            lat: "29.82745",
            fcode: "PPL",
          },
          {
            adminCode1: "DI",
            lng: "125.57361",
            geonameId: 1645457,
            toponymName: "Dili",
            countryId: "1966436",
            fcl: "P",
            population: 150000,
            countryCode: "TL",
            name: "Dili",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "DI",
            },
            countryName: "Timor-Leste",
            fcodeName: "capital of a political entity",
            adminName1: "Díli",
            lat: "-8.55861",
            fcode: "PPLC",
          },
          {
            adminCode1: "IA",
            lng: "-91.33098",
            geonameId: 4853722,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 471,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "IA",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Iowa",
            lat: "42.42971",
            fcode: "PPL",
          },
          {
            adminCode1: "MN",
            lng: "-95.21111",
            geonameId: 5024164,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 68,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "MN",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Minnesota",
            lat: "44.59913",
            fcode: "PPL",
          },
          {
            adminCode1: "OH",
            lng: "-84.60522",
            geonameId: 4510018,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 0,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "OH",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Ohio",
            lat: "39.09506",
            fcode: "PPL",
          },
          {
            adminCode1: "NY",
            lng: "-74.91599",
            geonameId: 5114824,
            toponymName: "Delhi",
            countryId: "6252001",
            fcl: "P",
            population: 3157,
            countryCode: "US",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "NY",
            },
            countryName: "United States",
            fcodeName: "seat of a second-order administrative division",
            adminName1: "New York",
            lat: "42.27814",
            fcode: "PPLA2",
          },
          {
            adminCode1: "08",
            lng: "-80.49968",
            geonameId: 5937522,
            toponymName: "Delhi",
            countryId: "6251999",
            fcl: "P",
            population: 0,
            countryCode: "CA",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "ON",
            },
            countryName: "Canada",
            fcodeName: "populated place",
            adminName1: "Ontario",
            lat: "42.8501",
            fcode: "PPL",
          },
          {
            adminCode1: "35",
            lng: "81.32847",
            geonameId: 10531612,
            toponymName: "Delhi",
            countryId: "1269750",
            fcl: "P",
            population: 0,
            countryCode: "IN",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "MP",
            },
            countryName: "India",
            fcodeName: "populated place",
            adminName1: "Madhya Pradesh",
            lat: "24.73392",
            fcode: "PPL",
          },
          {
            adminCode1: "35",
            lng: "81.58003",
            geonameId: 10532476,
            toponymName: "Delhi",
            countryId: "1269750",
            fcl: "P",
            population: 0,
            countryCode: "IN",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "MP",
            },
            countryName: "India",
            fcodeName: "populated place",
            adminName1: "Madhya Pradesh",
            lat: "24.63427",
            fcode: "PPL",
          },
          {
            adminCode1: "35",
            lng: "81.57507",
            geonameId: 10532517,
            toponymName: "Delhi",
            countryId: "1269750",
            fcl: "P",
            population: 0,
            countryCode: "IN",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "MP",
            },
            countryName: "India",
            fcodeName: "populated place",
            adminName1: "Madhya Pradesh",
            lat: "24.6444",
            fcode: "PPL",
          },
          {
            adminCode1: "OH",
            lng: "-83.15075",
            geonameId: 5167687,
            toponymName: "Radnor",
            countryId: "6252001",
            fcl: "P",
            population: 201,
            countryCode: "US",
            name: "Radnor",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "OH",
            },
            countryName: "United States",
            fcodeName: "populated place",
            adminName1: "Ohio",
            lat: "40.38423",
            fcode: "PPL",
          },
          {
            adminCode1: "06",
            lng: "97.37457",
            geonameId: 1281378,
            toponymName: "Delingha",
            countryId: "1814991",
            fcl: "P",
            population: 0,
            countryCode: "CN",
            name: "Delhi",
            fclName: "city, village,...",
            adminCodes1: {
              ISO3166_2: "QH",
            },
            countryName: "China",
            fcodeName: "seat of a third-order administrative division",
            adminName1: "Qinghai",
            lat: "37.376",
            fcode: "PPLA3",
          },
        ],
      }),
  })
);

describe("getGeoData to get the lattitude and longitude given a search term", () => {
  test("Testing the validateForm() function with a link, should return false", async () => {
    expect(await getGeoData("Delhi")).toEqual({
      lat: "28.65195",
      lon: "77.23149",
    });
  });
});
